## 00. PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0.dev20230709


### Introduction to Tensors

#### I. Creating Tensors

PyTorch tensors are created using `torch.tensor()`
https://pytorch.org/docs/stable/tensors.html

**1. Scalar**

In [2]:
# Scalar
scalar = torch.tensor(7)    # got tensor data type
scalar

tensor(7)

In [3]:
# a scalar has no dimensions -> a single number
scalar.ndim

0

In [4]:
# to get tensor back as python int (the value)
scalar.item()

7

**2. Vector**

In [5]:
vector = torch.tensor([7.,7])
print(vector)
print('dimension:', vector.ndim)    # number of pairs of closing square brackets
print('shape:', vector.shape)

tensor([7., 7.])
dimension: 1
shape: torch.Size([2])


**3. Matrix**

In [6]:
MATRIX = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(MATRIX)
print('dim:', MATRIX.ndim)
print('shape:', MATRIX.shape)
print('MATRIX[1]:', MATRIX[1])

tensor([[1, 2, 3],
        [4, 5, 6]])
dim: 2
shape: torch.Size([2, 3])
MATRIX[1]: tensor([4, 5, 6])


In [7]:
T = torch.tensor([[[1., 2.],
                   [3., 4.],
                   [5., 6.],
                   [7., 8.]]])
print(T)
print(T.shape)
print(T[0].shape)

tensor([[[1., 2.],
         [3., 4.],
         [5., 6.],
         [7., 8.]]])
torch.Size([1, 4, 2])
torch.Size([4, 2])


**Usually, naming: scalar and vector -> lower cases; matrix and tensor -> upper cases.**

**5. Random tensors**

- why random tensors?
- A: the way of many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data.

`Start with random numbers -> look at data -> updata random numbers -> look at data -> updata random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [8]:
# Random tensors
randint_tensor = torch.randint(5, (3,3))
print(randint_tensor)

rand_tensor = torch.rand(3, 4)  # shape: 3 x 4
print(rand_tensor)

tensor([[3, 2, 3],
        [4, 1, 3],
        [0, 3, 3]])
tensor([[0.4674, 0.3300, 0.0407, 0.3588],
        [0.0790, 0.7286, 0.0539, 0.1555],
        [0.8406, 0.2808, 0.3330, 0.7673]])


In [9]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224,224,3))   # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

**6. Zeros and Ones**

In [10]:
# all zeros
zero = torch.zeros(size = (3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
zero * rand_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [12]:
# all ones
ones = torch.ones(size = (3,4))
print(ones)

# default datatype
print('Default datatype of ones is:', ones.dtype)
print('Default datatype of rand_tensor is:', rand_tensor.dtype)
print('Default datatype of randint_tensor is:', randint_tensor.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Default datatype of ones is: torch.float32
Default datatype of rand_tensor is: torch.float32
Default datatype of randint_tensor is: torch.int64


**7. Create a range of tensors and tensors-like**


In [13]:
# torch.range() -> get deprecated message
# use torch.arange()
print(torch.arange(0, 10))

one_to_ten = torch.arange(start=1, end=11, step=3)
print(one_to_ten)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 1,  4,  7, 10])


In [14]:
# tensors like
# want to replicate a particular shape of a tensor, 
# but don't want to explicitly define the shape
new_zeros = torch.zeros_like(input=one_to_ten)
new_zeros
# zeros in the same shape as one_to_ten

tensor([0, 0, 0, 0])

#### II. Tensor datatypes

Presion in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [15]:
# Float 32 tensor

# float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float16)
# -> tensor([3., 6., 9.], dtype=torch.float16)

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,        # what data type is the tensor
                               device=None,         # what device is your tensor on, e.g., "cpu" / "cuda"?
                               requires_grad=False) # whether or not to track gradients with tensors operations

print(float_32_tensor)
print(float_32_tensor.dtype)

tensor([3., 6., 9.])
torch.float32


In [16]:
# change the tensor datatype

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [17]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [18]:
int_32_torch = torch.tensor([3,4,5], dtype=torch.int32)
int_32_torch

tensor([3, 4, 5], dtype=torch.int32)

In [19]:
float_32_tensor * int_32_torch

tensor([ 9., 24., 45.])

#### III. Get information from tensors (Attributes)

**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right data type (some) -> use `tendor.dtype` to get data type
2. not right shape -> use `tendor.shape`
3. not on the right device -> use `tendor.device`

In [20]:
some_tensor = torch.rand(3,4)
print(some_tensor)

# size() -> function??
print('size:', some_tensor.size())
print('shape:', some_tensor.shape)
print('device:', some_tensor.device)
print('dtype:', some_tensor.dtype)

tensor([[0.4694, 0.9842, 0.1525, 0.5335],
        [0.6430, 0.4736, 0.6738, 0.9256],
        [0.0782, 0.5546, 0.3955, 0.8083]])
size: torch.Size([3, 4])
shape: torch.Size([3, 4])
device: cpu
dtype: torch.float32


#### IV. Manipulate Tensors (tensor operations)

1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix multiplication (dot product)

In [21]:
tensor = torch.tensor([1, 2, 3])
# add 10
tensor + 10

tensor([11, 12, 13])

In [22]:
# multiply by 10
tensor * 10

tensor([10, 20, 30])

In [23]:
# sub 10
tensor - 10

tensor([-9, -8, -7])

In [24]:
# pytorch buildin functions
print(torch.mul(tensor, 10))
print(torch.add(tensor, 10))
print(torch.sub(tensor, 10))
print(torch.subtract(tensor, 10))
print(torch.div(tensor, 10))

tensor([10, 20, 30])
tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([-9, -8, -7])
tensor([0.1000, 0.2000, 0.3000])


**(1) Element-wise multiplication**

In [25]:
print(tensor, '*', tensor,' =', tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])  = tensor([1, 4, 9])


**(2) Matrix multiplication**

**Rules:** (x,y) @ (y,z) -> (x, z)

**To transpose a matrix:** tensor.T 

In [26]:
print(torch.matmul(tensor, tensor))
# torch.mm(tensor, tensor)  -> shortcut

# Or
print(tensor @ tensor)

tensor(14)
tensor(14)


In [27]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 459 µs, sys: 517 µs, total: 976 µs
Wall time: 581 µs


In [28]:
# faster
%%time
torch.matmul(tensor, tensor)

UsageError: Line magic function `%%time` not found.


In [29]:
# transpose operation
t_A = torch.tensor([[1,2],
                    [3,4],
                    [5,6]])

t_B = torch.tensor([[7,10],
                    [8,11],
                    [9,12]])

t_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [30]:
t_A @ t_B.T

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Tensor Aggregation

#### I. Find min, max, mean & sum

In [31]:
torch.min(t_B), t_B.min()

(tensor(7), tensor(7))

In [32]:
torch.max(t_B), t_B.max()

(tensor(12), tensor(12))

In [33]:
# torch.mean(t_B)   -> type error
# t_B.mean()        -> type error

# !! mean(): Input dtype must be either a floating point or complex dtype

torch.mean(t_B.type(torch.float32)), t_B.type(torch.float32).mean()


(tensor(9.5000), tensor(9.5000))

In [34]:
torch.sum(t_B), t_B.sum()

(tensor(57), tensor(57))

#### II. Find positional min and max

In [35]:
x = torch.tensor([2,5,7,3,1,5,6,9,40,20])
print('x.argmin():', x.argmin())
print('x.argmax():', x.argmax())

x.argmin(): tensor(4)
x.argmax(): tensor(8)


In [36]:
x[4], x[8]

(tensor(1), tensor(40))

### Reshaping, stacking, squeezing and unsqueezing

* Reshaping
    - reshapes an input tensor to a defined shape
* View 
    - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking 
    - concatenates a sequence of tensors along a new dimention *// all tensors need to be of the same size*
    - vstack (combine on the top of each other) & hstack (side by side)
* Squeezing
    - remove all `1` dimensions from a tensor
* Unsqueezing
    - remallove all `1` dimensions to a target tensor
* Permute
    - return a view of the original tensor `input` with dimensions permuted (swapped) in a way
    - rearrange the dimensions of a target tensor in a specified order

**1. Reshape**

In [37]:
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [38]:
# add an extra dimension
x_reshape = x.reshape(1,10)
x_reshape, x_reshape.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [39]:
x_reshape1 = x.reshape(10,1)
x_reshape1, x_reshape1.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [40]:
x2 = x.reshape(5,2)
x2, x2.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

**2. View**

In [41]:
# change the view

# view -> shares the memory with the original tensor
# just a different view of x??
z = x.view(1, 10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [42]:
# changing z changes x
z[:, 0] = 11
z, x

(tensor([[11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

**3. Stack**

(1) stack on the top

In [43]:
x_stack_top = torch.stack([x, x, x, x], dim=0)
x_stack_top

tensor([[11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [44]:
x_stack_top = torch.stack([x, x, x, x], dim=1)
x_stack_top

tensor([[11., 11., 11., 11.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [45]:
# equivalent to dim = 0
x_vstack = torch.vstack([x, x, x, x])
x_vstack

tensor([[11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

(2) side by side

In [46]:
x_hstack = torch.hstack([x, x, x, x])
x_hstack

tensor([11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.,  2.,  3.,  4.,
         5.,  6.,  7.,  8.,  9., 10., 11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,
         9., 10., 11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

**4. Squeeze & Unsqueeze**

In [47]:
x = torch.zeros(2, 1, 2, 1, 2)
x, x.shape

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [48]:
y = torch.squeeze(x)
y, y.size()

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

In [49]:
# squeeze only once?
y = torch.squeeze(x, 1)
y, y.size()

(tensor([[[[0., 0.]],
 
          [[0., 0.]]],
 
 
         [[[0., 0.]],
 
          [[0., 0.]]]]),
 torch.Size([2, 2, 1, 2]))

In [50]:
# another example
x = torch.arange(1., 11.)
x_reshape = x.reshape(1,10)
x_reshape, x_reshape.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [51]:
# x_squeeze = torch.squeeze(x)
x_squeeze = x.squeeze()
x_squeeze, x_squeeze.size()

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [52]:
# unsqueeze
x_unsqueeze = x_squeeze.unsqueeze(dim = 0)
x_unsqueeze, x_unsqueeze.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [53]:
x_unsqueeze1 = x_squeeze.unsqueeze(dim = 1)
x_unsqueeze1, x_unsqueeze1.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

**5. Permute**

common use: image

In [54]:
x = torch.randn(2, 3, 4)
x, x.shape

(tensor([[[-1.5395, -1.0529,  0.4009, -0.5693],
          [ 1.2223, -0.2391,  0.7210,  1.9236],
          [ 0.5752, -0.3841,  0.5913, -0.7708]],
 
         [[ 1.1592,  0.0388, -0.5122,  0.8123],
          [-0.3003,  1.0235, -1.6868,  0.9079],
          [-1.5621,  0.6095,  0.3171,  1.8831]]]),
 torch.Size([2, 3, 4]))

In [55]:
x_permute = torch.permute(x,(2, 0, 1))
# shifts axis 0->1, 1->2, 2->0
x_permute, x_permute.shape

(tensor([[[-1.5395,  1.2223,  0.5752],
          [ 1.1592, -0.3003, -1.5621]],
 
         [[-1.0529, -0.2391, -0.3841],
          [ 0.0388,  1.0235,  0.6095]],
 
         [[ 0.4009,  0.7210,  0.5913],
          [-0.5122, -1.6868,  0.3171]],
 
         [[-0.5693,  1.9236, -0.7708],
          [ 0.8123,  0.9079,  1.8831]]]),
 torch.Size([4, 2, 3]))

In [56]:
x_origin = torch.rand(size=(224,224,3))

# rearrange the sxis (or dim) order
x_permute = x_origin.permute(2, 0, 1)
x_permute.shape

torch.Size([3, 224, 224])

### Index (Select) data from tensors

similar to indexing with NumPy

In [57]:
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [58]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [59]:
x[0][1]

tensor([4, 5, 6])

In [60]:
x[0][2][1]

tensor(8)

In [61]:
# use ":" to select all of a target dimension
x[:, 1]

tensor([[4, 5, 6]])

In [62]:
# get all values of 1th and 1st dimensions but only index 1 of 2nd dimensions
x[:,:,1]
# the 1st column

tensor([[2, 5, 8]])

In [63]:
# get all values of the 0 dimension but only the 1 index value od 1sr and 2nd dimension
# difference with x[0][1][1] -> get back square bracket
x[:,1,1]

tensor([5])

### PyTorch tensors & NumPy

* Data in NumPy => PyTorch tensor: `torch.from_numpy(ndarray)`
* PyTorch tensor => NumPy: `torch.Tensor.numpy()`

**1. Numpy Array to tensor**

In [76]:
import numpy as np

array = np.arange(1.0, 8.0)
# warning: pytorch reflects numpy's default datatype of float64 unless specified otherwise
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [77]:
array.dtype

dtype('float64')

In [78]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [79]:
# change the value of array
# will not change the value of the tensor
array =  array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

**2. Tensor to Numpy array**

In [80]:
tensor = torch.ones(7)
# numpy -> reflects the original dtype of what tensor set as
numpy_arr = tensor.numpy()
tensor, numpy_arr

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [81]:
# change tensor
# will not change the value of numpy
tensor = tensor + 1
tensor, numpy_arr

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))