## 00. PyTorch Fundamentals

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0.dev20230709


### Introduction to Tensors

#### I. Creating Tensors

PyTorch tensors are created using `torch.tensor()`
https://pytorch.org/docs/stable/tensors.html

**1. Scalar**

In [2]:
# Scalar
scalar = torch.tensor(7)    # got tensor data type
scalar

tensor(7)

In [3]:
# a scalar has no dimensions -> a single number
scalar.ndim

0

In [4]:
# to get tensor back as python int (the value)
scalar.item()

7

**2. Vector**

In [5]:
vector = torch.tensor([7.,7])
print(vector)
print('dimension:', vector.ndim)    # number of pairs of closing square brackets
print('shape:', vector.shape)

tensor([7., 7.])
dimension: 1
shape: torch.Size([2])


**3. Matrix**

In [6]:
MATRIX = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(MATRIX)
print('dim:', MATRIX.ndim)
print('shape:', MATRIX.shape)
print('MATRIX[1]:', MATRIX[1])

tensor([[1, 2, 3],
        [4, 5, 6]])
dim: 2
shape: torch.Size([2, 3])
MATRIX[1]: tensor([4, 5, 6])


In [7]:
T = torch.tensor([[[1., 2.],
                   [3., 4.],
                   [5., 6.],
                   [7., 8.]]])
print(T)
print(T.shape)
print(T[0].shape)

tensor([[[1., 2.],
         [3., 4.],
         [5., 6.],
         [7., 8.]]])
torch.Size([1, 4, 2])
torch.Size([4, 2])


**Usually, naming: scalar and vector -> lower cases; matrix and tensor -> upper cases.**

**5. Random tensors**

- why random tensors?
- A: the way of many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data.

`Start with random numbers -> look at data -> updata random numbers -> look at data -> updata random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [8]:
# Random tensors
randint_tensor = torch.randint(5, (3,3))
print(randint_tensor)

rand_tensor = torch.rand(3, 4)  # shape: 3 x 4
print(rand_tensor)

tensor([[3, 2, 0],
        [1, 0, 3],
        [3, 4, 3]])
tensor([[0.7574, 0.9023, 0.1107, 0.1621],
        [0.0509, 0.2641, 0.6865, 0.0053],
        [0.5456, 0.5519, 0.3876, 0.5759]])


In [9]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224,224,3))   # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

**6. Zeros and Ones**

In [10]:
# all zeros
zero = torch.zeros(size = (3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
zero * rand_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [12]:
# all ones
ones = torch.ones(size = (3,4))
print(ones)

# default datatype
print('Default datatype of ones is:', ones.dtype)
print('Default datatype of rand_tensor is:', rand_tensor.dtype)
print('Default datatype of randint_tensor is:', randint_tensor.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Default datatype of ones is: torch.float32
Default datatype of rand_tensor is: torch.float32
Default datatype of randint_tensor is: torch.int64


**7. Create a range of tensors and tensors-like**


In [13]:
# torch.range() -> get deprecated message
# use torch.arange()
print(torch.arange(0, 10))

one_to_ten = torch.arange(start=1, end=11, step=3)
print(one_to_ten)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 1,  4,  7, 10])


In [14]:
# tensors like
# want to replicate a particular shape of a tensor, 
# but don't want to explicitly define the shape
new_zeros = torch.zeros_like(input=one_to_ten)
new_zeros
# zeros in the same shape as one_to_ten

tensor([0, 0, 0, 0])

#### II. Tensor datatypes

Presion in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [21]:
# Float 32 tensor

# float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float16)
# -> tensor([3., 6., 9.], dtype=torch.float16)

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,        # what data type is the tensor
                               device=None,         # what device is your tensor on, e.g., "cpu" / "cuda"?
                               requires_grad=False) # whether or not to track gradients with tensors operations

print(float_32_tensor)
print(float_32_tensor.dtype)

tensor([3., 6., 9.])
torch.float32


In [22]:
# change the tensor datatype

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [23]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [24]:
int_32_torch = torch.tensor([3,4,5], dtype=torch.int32)
int_32_torch

tensor([3, 4, 5], dtype=torch.int32)

In [26]:
float_32_tensor * int_32_torch

tensor([ 9., 24., 45.])

#### III. Get information from tensors (Attributes)

**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right data type (some) -> use `tendor.dtype` to get data type
2. not right shape -> use `tendor.shape`
3. not on the right device -> use `tendor.device`

In [28]:
some_tensor = torch.rand(3,4)
print(some_tensor)

# size() -> function??
print('size:', some_tensor.size())
print('shape:', some_tensor.shape)
print('device:', some_tensor.device)
print('dtype:', some_tensor.dtype)

tensor([[0.2475, 0.3446, 0.5173, 0.8071],
        [0.3974, 0.0242, 0.4886, 0.1459],
        [0.2525, 0.7337, 0.9072, 0.9760]])
size: torch.Size([3, 4])
shape: torch.Size([3, 4])
device: cpu
dtype: torch.float32
